### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by bolonio** [didomi/react#1]
Do you have any plans to create types to support typescript??

**Comment by MaximePlancke** [comment]
Hi Adrián,

We don't have it yet but we can definitely looking into it to make the implementation easier for you

**Comment by bolonio** [comment]
I would definitely appreciated it :)

**Comment by MaximePlancke** [comment]
I will be working on it. I will let you know once it is done

**Comment by MaximePlancke** [comment]
Thank you @venturachrisdev

@bolonio, the types has been added to the package. Let me know if you have any questions
