### ISSUE TITLE
`iabVersion` prop is missing in Types

### ISSUE THREAD

**Issue by apascal** [didomi/react#13]
Hi,

The SDK component provided with `1.5.0` includes a new `iabVersion` prop to support IAB v2 since #10.
However the `index.d.ts` file does not define such property, making it impossible to use in a typescript project without overriding the typing ourselves.

Could you please add this ?

Adrien

**Comment by apascal** [comment]
FYI @jawadst @MaximePlancke

**Comment by MaximePlancke** [comment]
Hi @apascal 

Thank you for your comment. The issue has been fixed.

Let me know if you have any issue
