### ISSUE TITLE
apiKey in didomiConfig ignored

### ISSUE THREAD

**Issue by giupas** [didomi/react#20]
In the `DidomiSDK.prototype.init` method the `apiKey` value is only from props

`var apiKey = this.props.apiKey;`

If omitted in `DidomiSDK` props and assigned value in didomiConfig (as in readme example), its value is ignored.

**Comment by MaximePlancke** [comment]
Hey Giuseppe,

Thank you for your comment. 
I have pushed a fix for the issue and will merge once it is reviewed

**Comment by MaximePlancke** [comment]
Hello @giupas ,

Changes have been pushed. Please update your package to version `1.6.0` 

Thank you
