### ISSUE TITLE
TS type for getUserStatus method

### ISSUE THREAD

**Issue by ludovicmnji** [didomi/react#31]
Could you add a minimal type for `Didomi.getUserStatus()` documented on your site : https://developers.didomi.io/cmp/web-sdk/reference/api#getuserstatus ? Currently this method and the return type is absent in `IDidomiObject`.

Also, I currently use the method `Didomi.getUserConsentStatusForAll()` to get `purposes` and `vendors` only. It's referenced in your `IDidomiObject` type but not in your website. Is it an oversight or the method is deprecated?

**Comment by jawadst** [comment]
@ludovicmnji We can update our types to better the documentation indeed.

`getUserConsentStatusForAll` was deprecated. It's still supported and we are not planning to remove it but we recommend switching to `getUserStatus` that covers the same cases and also adds more information (like legitimate interest).

**Comment by MaximePlancke** [comment]
@ludovicmnji The changes are merged. You can update the package to 1.7.3 

Thank you!
