### ISSUE TITLE
Whole app seems to flicker when didomi has loaded

### ISSUE THREAD

**Issue by Trennel** [didomi/react#37]
Hi there, 

I'm facing an issue where after giving consents for the first time (dialog) when I reload this page it seems that the whole application gets reloaded when Didomi loads. 
The whole application seems to flicker for a very short amount of time.

It certainly has to do with Didomi because when i remove import this issue is resolved.

Are you aware of this issue? Or is there a known way how to bypass?

Thanks alot! 

Lennert

**Comment by jawadst** [comment]
@Trennel We would need more information to investigate as that is not an issue that we have seen before.

Any chance you could share a test page that reproduces the issue? Also, do you have any logic running when Didomi is ready and that could cause your app to re-render?

**Comment by Trennel** [comment]
Thanks for fast response. It seems to be an error on our end. You can close this ticket. We've kinda figured it out. 
It seems to be a problem with external dependencies loading didomi twice.

**Comment by jawadst** [comment]
@Trennel Thanks for keeping us updated!
