### ISSUE TITLE
Incorrect Typescript type for IUserConsentStatus

### ISSUE THREAD

**Issue by ludovicmnji** [didomi/react#4]
`IUserConsentStatus` type is incorrect because `consentStatus` object returns an object with `vendors`(with a 's'), not `vendor`.

**Comment by jawadst** [comment]
Thanks for the report @ludovicmnji 

@MaximePlancke will take a look once he's back! (currently OOO)

**Comment by MaximePlancke** [comment]
Hi @ludovicmnji 

Thank you for the feedback. We have just published a new version 1.3.2 with the fix :)
