### ISSUE TITLE
argument 'consentToken' of 'onConsentChanged' value is not a string but a CWT from didomi/cwt-node

### ISSUE THREAD

**Issue by walid-mrtn** [didomi/react#45]
Hey,
I'm having a issue with version 1.7.3, using didomi/react with typescript:

when I log the token, like you do in this example
`onConsentChanged={cwtToken => console.log('A consent has been given/withdrawn', cwtToken)}`

I get an object with this structure:
```
{
consents: (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
issuer: null
user_id: string
user_id_hash_method: null
user_id_type: null
version: 1
}
```
This is a CWT from the didomi/cwt-node lib.
But the type [here](https://github.com/didomi/react/blob/26831622d559959a09dfcb8ccd9cc43ca2a2a5d4/index.d.ts#L126) is a string?

Do we have to update to use a CWT for the 'onConsentChanged' callback (and you types need to be updated too), or is this an error in the response from your service?

Thanks

Walid

**Comment by sevriugin** [comment]
Close this issue with merged  PR. Summary of changes

- update `OnConsentChangedFunction` type definition in index.d.ts file;
- update @didomi/react version from `1.8.0` to `1.8.1` in `package.json'.
