### ISSUE TITLE
Total blocking time (and FID) when load your SDK

### ISSUE THREAD

**Issue by ale-grosselle** [didomi/react#56]
Hello everyone!
We saw in our web site a strange behavior, your sdk block the main thread over 100 ms and our TBT (lighthouse) and FID core vitals are not good:
![Schermata 2022-06-25 alle 18 11 32](https://user-images.githubusercontent.com/6173088/175781910-6ab3c484-096b-4757-b5d6-dfe662de5282.png)

Why do you think it is so heavy?
Can't you break it up into multiple tasks?
Is it possible to eventually run in a web worker?

**Comment by mihaisavezi** [comment]
Hey @ale-grosselle  have you found a fix for this?

**Comment by ale-grosselle** [comment]
Hey @mihaisavezi I opened some tickets to "Didomi" but they didn't help us a lot...

The problem is not related to this component but in their script which this component included in the web page.

The script is not open source and we can't help Ddidomi to fix the problem

**Comment by jawadst** [comment]
@mihaisavezi @ale-grosselle 
We haven't had much time to work on this topic last year (although we did implement performance optimizations for TCF publisher restrictions) but we appreciate the feedback and understand it's an important concern. This is pretty high in our roadmap for this semester. We have started exploring the question and looking at options internally to improve our impact on Core Web Vitals metrics.

As you mention, it'll probably be a mix of 1) optimizing our code for paths that are particularly slow and 2) executing parts of our processes in non-blocking ways (workers, pausing with setTimeout, etc.).

We'll keep you posted and be in touch if we need help testing/validating some of our optimizations.

cc @EdgardoRodriguezSolano @sevriugin

**Comment by jawadst** [comment]
Working closely with our clients, I am happy to report that we have implemented improvements/optimizations in 2023:

- Optimize the size of our SDK (build and serve separate bundle for modern browsers, better compression, etc.)
- Pause during long initialization or UI tasks to ensure a good TBT and INP
- Expose SDK performance metrics for better monitoring

Performance is an ongoing effort and we have more optimizations coming in 2024.

As this topic is not related to React or our React module, I am going to close this issue at this point. Feel free to reach to our Support team if you have further questions.
