### ISSUE TITLE
Please make a release so React 18 can be used

### ISSUE THREAD

**Issue by fabb** [didomi/react#57]
Hi,

the latest released version still references only React 16/17 as peer dependencies. It has already been fixed for React 18 on the master branch, but no release was made. Please release the current master branch state as 1.8.2 so we can update our client applications to React 18 without npm issues.

https://github.com/didomi/react/commit/cacd486f8264754dc0aa506e14009aa05973e131

**Comment by jawadst** [comment]
Hi @fabb 

Let me check with the team and we'll get that done

J
